version: '3'
services:
  web:
    # look for the Dockerfile in the current directory
    # build: .
    build: 
      # . is the current directory
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      # . means $(pwd)
      - .:/app

  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    #environment:
    #  - CI=true
    command: ["npm", "run", "test"]