FROM node:16-alpine

WORKDIR '/app'

COPY package.json .

RUN npm install

COPY . .

# To resolve a permission error during recompile
RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache

CMD ["npm", "run", "start"]


