name: Test
on:
  pull_request:
  push: { branches: feature }

env:
  TEST_TAG: ${{ secrets.DOCKER_USERNAME }}/docker-react:test
  LATEST_TAG: ${{ secrets.DOCKER_USERNAME }}/docker-react:latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      -
        name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          context: ./section7/frontend
          file: ./section7/frontend/Dockerfile.dev
          load: true
          tags: ${{ env.TEST_TAG }}
      -
        name: Test
        run: |
          docker run -e CI=true --rm ${{ env.TEST_TAG }} npm run test